name: cache-worker
channels:
  - defaults
dependencies:
  - pip=24.0
  - python=3.12.4
  - pip:
      - aiomysql==0.2.0
      - annotated-types==0.7.0
      - anyio==4.4.0
      - bcrypt==4.2.0
      - beautifulsoup4==4.12.3
      - blinker==1.8.2
      - certifi==2024.7.4
      - cffi==1.17.0
      - click==8.1.7
      - cryptography==43.0.0
      - fastapi==0.112.2
      - flask==3.0.3
      - flask-cors==4.0.1
      - greenlet==3.0.3
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.2
      - idna==3.8
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - markupsafe==2.1.5
      - playwright==1.45.1
      - pycparser==2.22
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pyee==11.1.0
      - pymysql==1.1.1
      - python-dotenv==1.0.1
      - sniffio==1.3.1
      - soupsieve==2.5
      - starlette==0.38.2
      - typing-extensions==4.12.2
      - uvicorn==0.30.6
      - websockets==13.0.1
      - werkzeug==3.0.4
