version: '3'
services:
  flask-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: flask-api
    restart: always
    ports:
      - "7001:8000"
    networks:
      - app-network
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - ENCRYPT_KEY=${ENCRYPT_KEY}
      - SECRET_KEY=${SECRET_KEY}


  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    container_name: react-app
    restart: always
    ports:
      - "7000:3000"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
