version: '3'
services:
  flask-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: flask-api
    restart: always
    ports:
      - "${PORT2}:8000"
    networks:
      - app-network
    env_file:
      - api/.env

  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    container_name: react-app
    restart: always
    ports:
      - "${PORT1}:3000"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
