version: '3'
services:
  flask-api:
    image: chrisdev20/cache-api:latest
    container_name: flask-api
    restart: always
    ports:
      - "${PORT1}:8000"
    networks:
      - app-network
    env_file:
      - api/.env

  react-app:
    image: chrisdev20/cache-react:latest
    container_name: react-app
    restart: always
    ports:
      - "${PORT2}:3000"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
