services:
  redis:
    image: redis:7
    container_name: cache-redis
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: cache-api
    restart: always
    ports:
      - "7001:8000"
    networks:
      - app-network

  react:
    build:
      context: ./react
      dockerfile: Dockerfile
    container_name: cache-react
    restart: always
    ports:
      - "7002:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
