name: cache
channels:
  - defaults
  - conda-forge
  - fastai
  - r
  - bioconda
dependencies:
  - python=3.12.2
  - pip
  - pip:
    - plaid-python
    - gunicorn
    - redis
    - flask
    - flask-cors
    - flask-sqlalchemy
    - flask-session
    - flask-bcrypt
    - opencv-python-headless
    - pymysql
    - python-dotenv
    - pytesseract
