name: cache
channels:
  - defaults
  - conda-forge
  - fastai
  - r
  - bioconda
dependencies:
  - python=3.9.18
  - pip=23.3.2
  - flask
  - flask-cors
  - flask-login
  - flask-sqlalchemy
  - opencv-python-headless
  - passlib
  - mysql-connector-python
  - python-dotenv
  - pyjwt
  - pytesseract
  - pip:
    - plaid-python
    - gunicorn
