"""changed users table

Revision ID: 7a263bd8d064
Revises: 7e8dacaea51b
Create Date: 2024-08-09 00:52:50.380131

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a263bd8d064'
down_revision = '7e8dacaea51b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('id')

    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=300), nullable=False),
    sa.Column('password', mysql.TEXT(), nullable=True),
    sa.Column('fg_user', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('fg_pass', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('pointer', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=True)

    # ### end Alembic commands ###
