"""fixed user

Revision ID: 81a1c530bb39
Revises: 03cea2863e94
Create Date: 2025-03-07 22:57:16.203176

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '81a1c530bb39'
down_revision = '03cea2863e94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_pay')
        batch_op.drop_column('cutoff_index')
        batch_op.drop_column('pointer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pointer', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('cutoff_index', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_pay', mysql.FLOAT(), nullable=True))

    # ### end Alembic commands ###
