"""cascade

Revision ID: dea19d3773a3
Revises: 49151283c7b7
Create Date: 2025-02-26 00:07:51.727054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea19d3773a3'
down_revision = '49151283c7b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.drop_constraint('shift_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'payslip', ['payslip_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('shift_ibfk_2', 'payslip', ['payslip_id'], ['id'])

    # ### end Alembic commands ###
