name: personal-finance-api
channels:
  - defaults
dependencies:
  - pip=24.0
  - python=3.12.4
  - pip:
      - alembic==1.13.2
      - bcrypt==4.2.0
      - blinker==1.8.2
      - cffi==1.17.0
      - click==8.1.7
      - cryptography==43.0.0
      - flask==3.0.3
      - flask-bcrypt==1.0.1
      - flask-cors==4.0.1
      - flask-login==0.6.3
      - flask-migrate==4.0.7
      - flask-sqlalchemy==3.1.1
      - greenlet==3.0.3
      - gunicorn==23.0.0
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - mako==1.3.5
      - markupsafe==2.1.5
      - packaging==24.1
      - pycparser==2.22
      - pyee==11.1.0
      - pymysql==1.1.1
      - python-dotenv==1.0.1
      - soupsieve==2.5
      - sqlalchemy==2.0.32
      - typing-extensions==4.12.2
      - werkzeug==3.0.3
