name: Send POST Request with Query Parameters

on:
  push:
    branches:
      - main  
jobs:
  send-post-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send POST request to Flask app
        run: |
          curl -X POST "${{secrets.IP_ADDRESS}}/deploy/deploy?name=personal-finance" \
          -H "Content-Type: application/json" \
